base_url = "http://nothing.com"
compile_sass = true
title = "even theme"
description = ""
highlight_code = true
generate_categories_pages = true
generate_tags_pages = true

[extra]
author = "Vincent"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "Even"
